### ISSUE TITLE
Command line option parsing

### ISSUE THREAD

**Issue by selfboot** [xuelangZF/AnnotatedShadowSocks#2]
The `getopt` module is the old-school command line option parser that supports the conventions established by the Unix function `getopt()`. It parses an argument sequence, such as sys.argv and returns a sequence of (option, argument) pairs and a sequence of non-option arguments.

Supported option syntax includes:

```
-a
-bval
-b val
--noarg
--witharg=val
--witharg val
```

The getopt function takes three arguments:

- The first argument is the sequence of arguments to be parsed. This usually comes from sys.argv[1:] (ignoring the program name in sys.arg[0]).
- The second argument is the option definition string for single character options. If one of the options requires an argument, its letter is followed by a colon.
- The third argument, if used, should be a sequence of the long-style option names. Long style options can be more than a single character, such as --noarg or --witharg. The option names in the sequence should not include the -- prefix. **If any long option requires an argument, its name should have a suffix of =**.

Ref:  
[getopt – Command line option parsing](https://pymotw.com/2/getopt/)  
[C-style parser for command line options](https://docs.python.org/2/library/getopt.html)

**Comment by selfboot** [comment]
For `demo.py`:

```python
import getopt
import sys

version = '1.0'
verbose = False
output_filename = 'default.out'

print 'ARGV      :', sys.argv[1:]

options, remainder = getopt.getopt(sys.argv[1:], 'o:v', ['output=', 
                                                         'verbose',
                                                         'version=',
                                                         ])
print 'OPTIONS   :', options

for opt, arg in options:
    if opt in ('-o', '--output'):
        output_filename = arg
    elif opt in ('-v', '--verbose'):
        verbose = True
    elif opt == '--version':
        version = arg

print 'VERSION   :', version
print 'VERBOSE   :', verbose
print 'OUTPUT    :', output_filename
print 'REMAINING :', remainder
```


> $ python demo.py --output=foo
ARGV      : ['--output=foo']
OPTIONS   : [('--output', 'foo')]
VERSION   : 1.0
VERBOSE   : False
OUTPUT    : foo
REMAINING : []
$ python demo.py --output
ARGV      : ['--output']
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    'version=',
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 88, in getopt
    opts, args = do_longs(opts, args[0][2:], longopts, args[1:])
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 156, in do_longs
    raise GetoptError('option --%s requires argument' % opt, opt)
getopt.GetoptError: option --output requires argument

**Comment by selfboot** [comment]
The [argparse](https://docs.python.org/2/library/argparse.html#module-argparse) module makes it easy to write user-friendly command-line interfaces. The program defines what arguments it requires, and argparse will figure out how to parse those out of sys.argv. The argparse module also automatically generates help and usage messages and issues errors when users give the program invalid arguments.
